[project]
name = "drtool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.6",
    "jinja2>=3.1.4",
    "pytest>=8.3.4",
    "ruff>=0.8.3",
    "uvicorn>=0.32.1",
]
